window.siteConfig = {
  businessName: "360 Memories",
  ownerName: "Randy Urizar",
  phoneNumber: "214-399-3188",
  phoneDisplay: "214-399-3188",
  email: "360memoriesdtx@gmail.com",
  serviceArea: "75234",
  instagram: "360memoriesdtx",
  instagramUrl: "https://instagram.com/360memoriesdtx",
  defaultLanguage: "es",
  packages: [
    { value: "1 Hour - $300", price: "$300" },
    { value: "2 Hours - $500", price: "$500" },
    { value: "3 Hours - $600", price: "$600" }
  ],
  translations: {
    es: {
      headerTag: "Experiencias 360 bilingues para eventos",
      callNow: "Llamar ahora",
      heroEyebrow: "Cabina 360 para eventos en Dallas",
      heroHeadline: "Haz que cada invitado se lleve un recuerdo que se sienta especial.",
      heroSubheadline:
        "360 Memories lleva energia, atencion personalizada y servicio bilingue a bodas, quinceaneras, cumpleanos, eventos corporativos y venues que quieren una experiencia inolvidable.",
      heroPillOne: "Espanol + English",
      heroPillTwo: "Montaje rapido en 30 min max",
      heroPillThree: "Perfecto para momentos memorables",
      primaryCta: "Verificar disponibilidad",
      heroCallCta: "Hablar por telefono",
      trustLabelOne: "1 a 3 horas",
      trustTextOne: "Paquetes simples y claros para tu evento",
      trustLabelTwo: "Atencion real",
      trustTextTwo: "Servicio personalizado para tus invitados",
      trustLabelThree: "Listo para evento",
      trustTextThree: "Demo-ready hoy, facil de reservar",
      visualLabelTop: "Hecho para celebrar",
      visualHeadline: "Diversion premium sin complicaciones",
      visualBody:
        "Una experiencia 360 moderna, facil de disfrutar y disenada para que tus invitados se sientan atendidos desde el primer video hasta el ultimo recuerdo.",
      setupStat: "minutos o menos para montar",
      packagesEyebrow: "Paquetes",
      packagesTitle: "Elige el tiempo ideal para tu fiesta",
      packagesIntro:
        "Precios directos, experiencia premium y un formato facil de comparar para reservar rapido.",
      packageOneLabel: "1 Hora",
      packageOneBody: "Ideal para eventos cortos, activaciones y celebraciones con flujo rapido.",
      packageTwoLabel: "2 Horas",
      packageTwoBody: "La opcion mas balanceada para mantener la energia y darle tiempo a mas invitados.",
      packageThreeLabel: "3 Horas",
      packageThreeBody: "Perfecto para eventos grandes donde quieres mas cobertura y mas momentos.",
      packageCta: "Me interesa este paquete",
      popularBadge: "Mas solicitado",
      galleryEyebrow: "Visuales",
      galleryTitle: "Espacio listo para mostrar tu proximo evento",
      galleryIntro:
        "Esta seccion esta preparada para fotos reales del negocio, pero ya transmite el look moderno y energico del servicio sin depender de archivos pesados.",
      galleryFeatureBadge: "Facil de actualizar",
      galleryFeatureTitle: "Cambia estas piezas por fotos reales en minutos",
      galleryFeatureBody:
        "La galeria usa bloques livianos para que puedas reemplazar imagenes despues sin tocar el diseno completo.",
      galleryTileOne: "Bodas y recepciones",
      galleryTileTwo: "Quinceaneras y cumpleanos",
      galleryTileThree: "Eventos corporativos",
      galleryTileFour: "Venues que quieren sorprender a sus invitados",
      customizerEyebrow: "Personaliza el look",
      customizerTitle: "Personaliza tu experiencia",
      customizerIntro: "Mira en segundos como podria verse tu evento dentro de una experiencia 360 hecha para tu ambiente.",
      customizerEventLabel: "Tipo de evento",
      customizerEventWedding: "Boda",
      customizerEventBirthday: "Cumpleanos",
      customizerEventCorporate: "Corporativo",
      customizerOverlayLabel: "Estilo de overlay",
      customizerOverlayMinimal: "Minimal",
      customizerOverlayElegant: "Elegante",
      customizerOverlayParty: "Party",
      customizerThemeLabel: "Tema de color",
      customizerThemeWarm: "Warm",
      customizerThemeDark: "Dark",
      customizerThemeBright: "Bright",
      valueEyebrow: "Por que reservar",
      valueTitle: "Una experiencia divertida, profesional y facil de contratar",
      valueIntro:
        "Lo importante no es solo grabar videos. Es crear un momento que haga sentir a tus invitados que su experiencia fue pensada con cuidado.",
      valueOneTitle: "Servicio bilingue real",
      valueOneBody:
        "Atendemos en espanol e ingles para que tus invitados y organizadores se sientan comodos durante todo el evento.",
      valueTwoTitle: "Momentos que si se recuerdan",
      valueTwoBody:
        "La cabina 360 convierte la participacion en un recuerdo compartible y divertido para todo tipo de celebracion.",
      valueThreeTitle: "Montaje rapido y simple",
      valueThreeBody:
        "Un solo operador, flujo claro y una instalacion rapida que ayuda a mantener tu evento en movimiento.",
      valueFourTitle: "Atencion personalizada",
      valueFourBody:
        "Cada evento recibe trato cercano para que cada invitado se vaya sintiendo valorado.",
      faqEyebrow: "FAQ",
      faqTitle: "Preguntas comunes antes de reservar",
      faqIntro: "Respuestas rapidas para ayudarte a decidir sin vueltas.",
      faqOneQuestion: "Cuanto tarda el montaje?",
      faqOneAnswer: "Normalmente hasta 30 minutos, dependiendo del acceso y del espacio del venue.",
      faqTwoQuestion: "En que areas dan servicio?",
      faqTwoAnswer:
        "Estamos enfocados en el area de Dallas alrededor de 75234 y podemos confirmar cobertura segun la ubicacion de tu evento.",
      faqThreeQuestion: "Que incluye la experiencia?",
      faqThreeAnswer:
        "Una experiencia 360 personalizada, atencion durante la activacion y un flujo pensado para que tus invitados disfruten facilmente.",
      faqFourQuestion: "Con cuanta anticipacion debo reservar?",
      faqFourAnswer:
        "Lo ideal es reservar lo antes posible para asegurar fecha, especialmente en temporadas altas y fines de semana.",
      faqFiveQuestion: "Que duraciones tienen los paquetes?",
      faqFiveAnswer:
        "Puedes elegir 1 hora por $300, 2 horas por $500 o 3 horas por $600 segun el tamano y ritmo de tu evento.",
      serviceEyebrow: "Area de servicio",
      serviceTitle: "Dallas y zonas cercanas",
      serviceIntro: "Atendemos eventos alrededor de Dallas con base en el area 75234.",
      serviceZipLabel: "Base de servicio",
      serviceBody:
        "Si tu evento es en Dallas o cerca de 75234, envianos la fecha y el venue para confirmar disponibilidad y cobertura.",
      formEyebrow: "Reserva tu fecha",
      formTitle: "Cuentanos sobre tu evento",
      formIntro:
        "Completa este formulario y te contactamos rapido para revisar disponibilidad, paquete ideal y detalles del evento.",
      fieldName: "Nombre",
      fieldEventType: "Tipo de evento",
      fieldEventDate: "Fecha del evento",
      fieldPhone: "Telefono",
      fieldEmail: "Correo electronico",
      fieldVenue: "Venue / Ciudad",
      fieldGuestCount: "Cantidad de invitados",
      fieldPackage: "Paquete de interes",
      fieldMessage: "Mensaje",
      formCta: "Verificar disponibilidad",
      mobileStickyCta: "Reservar ahora",
      footerCopy: " | Experiencias 360 bilingues para eventos inolvidables",
      thanksEyebrow: "Solicitud enviada",
      thanksTitle: "Gracias por contactarnos",
      thanksBody:
        "Recibimos tu informacion y te responderemos pronto para confirmar disponibilidad y detalles de tu evento.",
      thanksBackToForm: "Volver al formulario"
    },
    en: {
      headerTag: "Bilingual 360 event experiences",
      callNow: "Call now",
      heroEyebrow: "Dallas 360 booth experiences",
      heroHeadline: "Give every guest a memory that feels unforgettable.",
      heroSubheadline:
        "360 Memories brings energy, personal service, and bilingual support to weddings, quinceaneras, birthdays, corporate events, and venues that want a standout experience.",
      heroPillOne: "Spanish + English",
      heroPillTwo: "Fast 30-minute max setup",
      heroPillThree: "Built for memorable moments",
      primaryCta: "Check availability",
      heroCallCta: "Call now",
      trustLabelOne: "1 to 3 hours",
      trustTextOne: "Simple package options for your event",
      trustLabelTwo: "Personal care",
      trustTextTwo: "Thoughtful service for every guest",
      trustLabelThree: "Ready to book",
      trustTextThree: "Demo-ready now and easy to launch live",
      visualLabelTop: "Built for celebrations",
      visualHeadline: "Premium fun without the hassle",
      visualBody:
        "A modern 360 booth experience that is easy to enjoy and designed to make guests feel taken care of from the first clip to the last memory.",
      setupStat: "minutes or less for setup",
      packagesEyebrow: "Packages",
      packagesTitle: "Choose the right event window",
      packagesIntro:
        "Straightforward pricing, premium presentation, and a clear comparison that helps people book faster.",
      packageOneLabel: "1 Hour",
      packageOneBody: "Best for shorter celebrations, activations, and fast-moving guest flow.",
      packageTwoLabel: "2 Hours",
      packageTwoBody: "The best balance for keeping energy high and giving more guests time to join in.",
      packageThreeLabel: "3 Hours",
      packageThreeBody: "Perfect for larger events where you want more coverage and more moments captured.",
      packageCta: "I want this package",
      popularBadge: "Most popular",
      galleryEyebrow: "Visuals",
      galleryTitle: "A gallery section ready for your next event",
      galleryIntro:
        "This section is ready for real business photos later, while already giving the site a modern, energetic look without heavy assets.",
      galleryFeatureBadge: "Easy to update",
      galleryFeatureTitle: "Swap these blocks for real photos in minutes",
      galleryFeatureBody:
        "The gallery is built with lightweight placeholders so future image updates stay simple and fast.",
      galleryTileOne: "Weddings and receptions",
      galleryTileTwo: "Quinceaneras and birthdays",
      galleryTileThree: "Corporate events",
      galleryTileFour: "Venues that want guests to feel wowed",
      customizerEyebrow: "Customize the look",
      customizerTitle: "Customize your experience",
      customizerIntro: "See how your event could look in seconds with a quick phone-style preview built around your vibe.",
      customizerEventLabel: "Event type",
      customizerEventWedding: "Wedding",
      customizerEventBirthday: "Birthday",
      customizerEventCorporate: "Corporate",
      customizerOverlayLabel: "Overlay style",
      customizerOverlayMinimal: "Minimal",
      customizerOverlayElegant: "Elegant",
      customizerOverlayParty: "Party",
      customizerThemeLabel: "Color theme",
      customizerThemeWarm: "Warm",
      customizerThemeDark: "Dark",
      customizerThemeBright: "Bright",
      valueEyebrow: "Why book us",
      valueTitle: "A fun, professional experience that feels easy to book",
      valueIntro:
        "This is not just about recording videos. It is about creating a moment that makes guests feel like their experience really mattered.",
      valueOneTitle: "True bilingual service",
      valueOneBody:
        "We support guests and hosts in Spanish and English so everyone feels comfortable throughout the event.",
      valueTwoTitle: "Memories people actually keep",
      valueTwoBody:
        "The 360 booth turns participation into a fun, shareable moment for all kinds of celebrations.",
      valueThreeTitle: "Fast, simple setup",
      valueThreeBody:
        "One operator, a clean process, and a quick setup that keeps your event moving without extra stress.",
      valueFourTitle: "Personalized attention",
      valueFourBody:
        "Every booking gets real care so each guest leaves feeling noticed and appreciated.",
      faqEyebrow: "FAQ",
      faqTitle: "Common questions before you book",
      faqIntro: "Quick answers to help you decide with confidence.",
      faqOneQuestion: "How long does setup take?",
      faqOneAnswer: "Setup usually takes up to 30 minutes depending on venue access and available space.",
      faqTwoQuestion: "What areas do you serve?",
      faqTwoAnswer:
        "We focus on the Dallas area around 75234 and can confirm coverage based on your event location.",
      faqThreeQuestion: "What is included in the experience?",
      faqThreeAnswer:
        "A personalized 360 booth experience, live event support, and a smooth guest flow designed to keep the experience easy and fun.",
      faqFourQuestion: "How far in advance should I book?",
      faqFourAnswer:
        "Booking as early as possible is best, especially for peak seasons and weekend event dates.",
      faqFiveQuestion: "What package lengths are available?",
      faqFiveAnswer:
        "You can choose 1 hour for $300, 2 hours for $500, or 3 hours for $600 based on your event size and timeline.",
      serviceEyebrow: "Service area",
      serviceTitle: "Dallas and nearby areas",
      serviceIntro: "We serve events around Dallas with a home base in 75234.",
      serviceZipLabel: "Service base",
      serviceBody:
        "If your event is in Dallas or near 75234, send over your date and venue so we can confirm availability and travel coverage.",
      formEyebrow: "Book your date",
      formTitle: "Tell us about your event",
      formIntro:
        "Fill out the form and we will reach out quickly to review availability, your package fit, and event details.",
      fieldName: "Name",
      fieldEventType: "Event type",
      fieldEventDate: "Event date",
      fieldPhone: "Phone",
      fieldEmail: "Email",
      fieldVenue: "Venue / City",
      fieldGuestCount: "Guest count",
      fieldPackage: "Package interest",
      fieldMessage: "Message",
      formCta: "Check availability",
      mobileStickyCta: "Check availability",
      footerCopy: " | Bilingual 360 experiences for unforgettable events",
      thanksEyebrow: "Request sent",
      thanksTitle: "Thanks for reaching out",
      thanksBody:
        "We received your info and will follow up soon to confirm availability and event details.",
      thanksBackToForm: "Back to form"
    }
  }
};
